[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  branch = "master"
  name = "github.com/brutella/hc"


[[constraint]]
  name = "github.com/stianeikeland/go-rpio"
  version = "^4.2.0"
